### ISSUE TITLE
Avro examples not usable, how to use Avro?

### ISSUE THREAD

**Issue by Samrose-Ahmed** [jorgecarleitao/arrow2#1232] opened 2022-08-18 19:44 UTC
The Avro examples/documentation seems incorrect. Looks like it references private crates/functions. How would one read/write Avro?

**Comment by jorgecarleitao** [comment] 2022-08-18 19:48
Hey!

Could you compile with `--features io_avro`? We [document](https://docs.rs/arrow2/latest/arrow2/io/index.html) that certain modules require feature flags.

The issue here is that atm there is no way in Rust to have no default features and at the same time automatically pass `--features` to the example (i.e. cargo.toml does not allow specifying which features are required for each example)

**Comment by Samrose-Ahmed** [comment] 2022-08-18 19:58
Hi I did compile with `io_avro`.

If I use the code:

```rust
use arrow2::io::avro::avro_schema::file::Block;
use arrow2::io::avro::avro_schema::read_async::{block_stream, decompress_block, read_metadata};
use arrow2::io::avro::read::{deserialize, infer_schema};
```
I get error

```
no `avro_schema` in `io::avro`
```

Also 
```
function `infer_schema` is private
```

**Comment by jorgecarleitao** [comment] 2022-08-18 20:14
just to check, is this the current release or the latest main? I am being unable to reproduce this in both cases.

For example, check https://github.com/DataEngineeringLabs/arrow2-benches/tree/latest, where a Cargo.toml with the latest main and the `benches` containing the reader work as intended?

**Comment by jorgecarleitao** [comment] 2022-08-18 20:29
the main is still using 0.6, yes; I meant the branch "latest".

**Comment by jorgecarleitao** [comment] 2022-08-18 20:40
ohh, I now realize that I forgot to push the change locally. Really sorry about that :( Could you check the branch "latest" now?

**Comment by Samrose-Ahmed** [comment] 2022-08-19 07:23
Apologies if I'm misunderstanding but I don't see any branch called "latest" on https://github.com/jorgecarleitao/arrow2/branches ?

**Comment by Samrose-Ahmed** [comment] 2022-08-19 07:39
Changing my `Cargo.toml` to use the git repository instead of Cargo v 0.13.1 (`git = "https://github.com/jorgecarleitao/arrow2"`) seems to have fixed this issue. I guess the docs were for the git main not the 0.13.1 version.

**Comment by FireArrow** [comment] 2022-08-19 17:28
There are similar problems with the parquet examples, which are written for latest main, but doesn't work on 0.13.1 (the latest release as of writing this). This caused me more confusion than I want to admit. What about splitting the examples and the actual development so the examples can be merged as part of creating a release? Or at the very least mention the difference somehow?

**Comment by jorgecarleitao** [comment] 2022-08-20 04:57
Note that the examples are present in the released artifact for a specific version, https://docs.rs/crate/arrow2/latest/source/examples/ . We also tag every released version, so e.g. https://github.com/jorgecarleitao/arrow2/tree/v0.13.0 provides the examples for the released version. If I'm looking into the examples in the branch `main`, I would expect to get the examples compatible with `main`?

@Samrose-Ahmed glad that the issue is addressed. Note that I was not pointing to this repository in the comment above - https://github.com/DataEngineeringLabs/arrow2-benches/tree/latest

**Comment by FireArrow** [comment] 2022-08-20 06:46
What you are saying makes sense. But when trying this lib out the first place you look at is the [guide linked in the readme](https://jorgecarleitao.github.io/arrow2/io/parquet_read.html) which seems to be following `main`. not latest the release the readme was written for. Is there a way to view different branches on github.io, or something like that?

**Comment by jorgecarleitao** [comment] 2022-08-20 08:22
Ahhh, I see. I created https://github.com/jorgecarleitao/arrow2/pull/1233 to try to improve the situation. 

Essentially, after the PR, we will have:
* https://jorgecarleitao.github.io/arrow2/main/guide
* https://jorgecarleitao.github.io/arrow2/main/docs
* https://jorgecarleitao.github.io/arrow2/{tag}/guide
* https://jorgecarleitao.github.io/arrow2/{tag}/docs

where `{tag}` is a released version. I have to investigate if I can retroactively generate the old tags, but it seems unlikely.

**Comment by jorgecarleitao** [comment] 2022-08-22 06:31
@Samrose-Ahmed, @FireArrow, do you believe #1233 closes this issue?

**Comment by Samrose-Ahmed** [comment] 2022-08-22 06:35
Yes, thank you for the update.

**Comment by FireArrow** [comment] 2022-08-22 19:22
I agree! This solves the problem perfectly!

Thanks!

On 22 Aug 2022 08:35, Samrose ***@***.***> wrote:

Yes, thank you for the update.

**Closed** 2022-08-23 20:49 UTC
Labels: question
